language:
  - node_js

# Container-based infrastructure.
# http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "5.0"

branches:
  only:
    - master

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  # NOTE: **Cannot** have a space after `:` character in JSON string or else
  # YAML parser will fail to parse correctly.
  global:
    - ROWDY_OPTIONS='{ "client":{ "logger":true }, "server":{ "logger":true } }'
    - secure: RNc5J2RK3sBqx9UoQSORuqm57lmE3nGWsIyb3Yr9JG4PYcwBidFlZpT/pk5nvFNKfRjSe9hfXAeJRYRD8QqenG3YASDH278hdW+g1QyBJeorEZGwtDfqxtKfiif5yaULaYF7LjhAzIMlyqiz9NbbM7gwiwtlBkWRGenrwHJ2U9o=
    - secure: W5dyVnpoWwRIDkgkGza4VLnsghYGYdbP3U0sZY5Olp2Enx/AXijgYlmILbnef7lGV/lp3f0GT2JIYdiK0ESkrsgpltdu8YedAfB1Ld8vcQbt5KU/AQic1TQFwDKviVG3Wdqhyndd5kfP4tanGLjpeixdhYFAbApr7zjpCD1DTEE=
    - secure: ZFOUkBbo5MLheb/PeKevyj/4fTd4rBJFQebLxeFaCcRfK7iZfulRAG3Hi8r2VX0+eaV3iMy5e2oIui4Msrtxiu/U53R1TPm0K253qPghwRodMTdKqECgZnOqDBeytb/CgveOcxN3j4SgNQn6DnO32zH0tUcJbzhDdYBQT9fNz3s=
    - secure: GmmWm6z4Hg02ZCuy5pb9+yfWPKALnLjbh+H0s2UEihzepvKcgI4+BkRubWAfxbMLzISBLN+NF7i3KE/Sf81/OvskQp7M9Z91EucokUK7iFRHZBcAl6BJ7cY5WwJxpRjoIruUE0CgmHKEHjrKl9VkPMnu/7dK/2SxSDnPM1A4ims=
  matrix:
    - ROWDY_CHECK=1
    # Local
    - ROWDY_SETTINGS="local.phantomjs"
    - ROWDY_SETTINGS="local.firefox"
    # Sauce Labs
    - ROWDY_SETTINGS="sauceLabs.chrome_43_Windows_2012_R2_Desktop"
    - ROWDY_SETTINGS="sauceLabs.firefox_38_Windows_2012_R2_Desktop"
    - ROWDY_SETTINGS="sauceLabs.IE_9_Windows_2008_Desktop"
    - ROWDY_SETTINGS="sauceLabs.IE_10_Windows_2012_Desktop"
    - ROWDY_SETTINGS="sauceLabs.IE_11_Windows_2012_R2_Desktop"
    # Disable flaky test: https://github.com/FormidableLabs/rowdy/issues/32
    #- ROWDY_SETTINGS="sauceLabs.safari_7_OS_X_10_9_Desktop"
    # BrowserStack
    #
    # Disable BS until "The environment you requested was unavailable." errors
    # are figured out and/or subside.
    # https://github.com/FormidableLabs/rowdy/issues/34
    #- ROWDY_SETTINGS="browserStack.safari-mac"
    #- ROWDY_SETTINGS="browserStack.chrome-win7"

before_script:
  # Download selenium drivers.
  - npm run install-selenium

script:
  # Run the "check" script only once.
  - 'if [ "$ROWDY_CHECK" ]; then npm run check; else true; fi'
  # Try a different port!
  - 'if [ "$ROWDY_CHECK" ]; then ROWDY_OPTIONS="{ \"client\":{ \"logger\":true }, \"server\":{ \"logger\":true,\"port\":4321 } }" npm run test; else true; fi'

  # Different matrix of settings
  - '[ "$ROWDY_CHECK" ] || npm test'
